[package]
name = "mandelbroot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
softbuffer = "0.4.1"
tiny-skia = "0.11.3"
winit = "0.29.10"
